name: Rainix CI
on: [push]

jobs:
  rainix:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PRIVATE_KEY || secrets.PRIVATE_KEY_DEV }}
    steps:
      - uses: actions/checkout@v4

      - name: Install NodeJS v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Deps
        run:  npm install

      - name: Build Prod
        run:  npm run build-prod

      - name: Build Dev
        run:  npm run build

      - name: Lint
        run:  npm run lint

      # install playwright
      - name: Install Playwright
        run: npx playwright install

      # Run the desktop tests using headless setup
      - name: Desktop Extension Test
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test-desktop

      # Run the web extention tests
      - name: Web Extension Test
        run: npm run test-web