name: Standard Test

on: [push, pull_request]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Install deps
      - name: Install Dependencies
        run: npm install

      # Build the prod package
      - name: Build Prod
        run: npm run build-prod

      # Build the dev package
      - name: Build Dev
        run: npm run build

      # Lint the source code
      - name: Lint
        run: npm run lint

      # Lint the source code
      - name: Install Playwright
        run: npx playwright install

      # Run the desktop tests using headless setup
      - name: Desktop Extension Test
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test-desktop

      # Run the web extention tests
      - name: Web Extension Test
        run: npm run test-web