name: Standard Test

on: [push, pull_request]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Install deps
      - name: Install Dependencies
        run: npm install

      # Build the prod package
      - name: Build Prod
        run: npm run build-prod

      # Build the dev package
      - name: Build Dev
        run: npm run build

      # Lint the source code
      - name: Lint
        run: npm run lint

      # Set up display for tests
      - name: Start xvfb
        if: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"

      # Run the desktop extension tests
      - name: Desktop Extension Test
        run: npm run test-desktop
        env: 
          DISPLAY: ':99.0'

      # Run the web extention tests
      - name: Web Extension Test
        run: npm run test-web